### PR TITLE
Migrate to use v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
I've tried to migrate to use v0.14 Input/Output Plugin API.
This PR contains major update change.
Could you bump up minor version if releasing new version of gem?
And please refer http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12 before release new version.

Thanks,

Will fix https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/issues/54.

### CODE REVIEW

**Comment by cosmo0920** [comment]
But I removed `ConfigPlaceholders` support from these patches.
In v0.14, `ConfigPlaveholders` is discouraged to use.

**Comment by ryotarai** [comment]
Migrating to v0.14 API looks great but I recognize v0.14 is still experimental: https://www.fluentd.org/download
Dropping v0.12 support is too aggressive, I think

**Comment by cosmo0920** [comment]
How about this changes publishing with rc version?
pre version is not installed by default.

**Comment by cosmo0920** [comment]
v0.14 is stable now.
https://www.fluentd.org/blog/fluentd-v0.14.22-has-been-released

**Comment by cosmo0920** [comment]
I resolved conflicts.
Could you take a look?

**Comment by pantocrator27** [comment]
I would be interested in this being released 👍

**Comment by Seraf** [comment]
+1 that would be awesome as fluentd is now stable and distributed as v1.

**Comment by ryotarai** [comment]
released in v0.5.0.pre1

**Pull request merged**
