### PR TITLE
Support sts:AssumeRole

### PR DESCRIPTION
**Pull request by sampointer**
This change enables cross-account IAM authentication.

### CODE REVIEW

**Comment by sampointer** [comment]
Bump

**Comment by sampointer** [comment]
@ryotarai Bump - any chance of merging this?

**Comment by sampointer** [comment]
@ryotarai Bump - Please can you merge this? I've been using a private fork and build for 6 months now including this change and https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/pull/55

It would be extremely helpful if this now well-tested code could be merged to master and published as a release.

**Comment by ryotarai** [comment]
Thank you for your patch and I'm sorry to be late to merge.
I'll release new version

**Comment by ryotarai** [comment]
v0.3.8 is released

**Comment by sampointer** [comment]
Thank you so much for doing this.

If you could also merge and release both:

* https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/pull/55
* https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/pull/66

I will be able to run once again from your maintained version rather than my private fork.

Many thanks.

**Pull request merged**
